

CREATE OR ALTER PROC sp_update_GIA @maMA VARCHAR(10),
								   @gia MONEY
AS
BEGIN
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM MONAN WHERE MAMON = @maMA)
	BEGIN
		PRINT N'Món ăn không tồn tại'
		ROLLBACK TRAN
	END
	IF @gia < 0
	BEGIN
		 PRINT N'Giá không hợp lệ'
         ROLLBACK TRAN
	END
	WAITFOR DELAY '00:00:05'

	UPDATE MONAN
	SET GIA = @gia
	WHERE MAMON = @maMA
	IF @@TRANCOUNT > 0
		COMMIT TRAN
END
GO

CREATE OR ALTER PROC sp_select_MONAN @maDT VARCHAR(10)
AS
BEGIN
BEGIN TRAN
	IF NOT EXISTS (SELECT * FROM DOITAC WHERE ID_DOITAC = @maDT)
	BEGIN
		PRINT N'Đối tác không tồn tại'
		ROLLBACK TRAN
	END
	SELECT MA.MIEUTAMON,       MA.LOAIMONAN, MA.GIA
	FROM MONAN MA JOIN CHINHANH_DK CN 
	ON MA.CHINHANH = CN.ID_CHINHANH 
	JOIN DOITAC DT ON CN.DOITAC =  DT.ID_DOITAC
	WHERE DT.ID_DOITAC = @maDT
	IF @@TRANCOUNT > 0
		COMMIT TRAN
END