USE QL_BANHANG
GO

CREATE OR ALTER
PROC USP_DT_SL_CHINHANH
	@id_doitac char(10),
	@soluong int 
AS
SET TRAN ISOLATION LEVEL REPEATABLE READ 
BEGIN TRAN
	DECLARE @soluong_HT INT
	SET @soluong_HT = (SELECT SL_CHINHANH 
					   FROM DOITAC
					   WHERE DOITAC.ID_DOITAC= @id_doitac)

	IF (@soluong_HT = @soluong)
	BEGIN
		PRINT N'SỐ LƯỢNG CHI NHÁNH MUỐN ĐỔI TRÙNG VỚI CHI NHÁNH HIỆN TẠI !'
		ROLLBACK TRAN
		RETURN
	END

	WAITFOR DELAY '0:0:05'

	BEGIN TRY
		UPDATE DOITAC
		SET SL_CHINHANH = @soluong
		WHERE DOITAC.ID_DOITAC =@id_doitac
	END TRY

	BEGIN CATCH 
		DECLARE @ERROR VARCHAR(2000)
		SELECT @ERROR = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERROR, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH

COMMIT TRAN

GO
CREATE OR ALTER PROC USP_DT_NGUOIDAIDIEN
	@id_doitac char(10),
	@nguoidaidien nvarchar(20)

AS
SET TRAN ISOLATION LEVEL REPEATABLE READ 
BEGIN TRAN
	DECLARE @nguoidaidienhientai nvarchar(30)
	SET @nguoidaidienhientai = (SELECT NG_DAIDIEN
								FROM DOITAC
								WHERE ID_DOITAC=@id_doitac)
	
	IF (@nguoidaidienhientai = @nguoidaidienhientai)
	BEGIN
		PRINT N'TÊN NGƯỜI ĐẠI DIỆN MUỐN ĐỔI TRÙNG VỚI NGƯỜI ĐẠI DIỆN BÂY GIỜ '
		ROLLBACK TRAN
		RETURN
	END

	WAITFOR DELAY '0:0:05'

	BEGIN TRY
		UPDATE DOITAC
		SET NG_DAIDIEN = @nguoidaidien
		WHERE DOITAC.ID_DOITAC =@id_doitac
		
	END TRY

	BEGIN CATCH 
		DECLARE @ERROR VARCHAR(2000)
		SELECT @ERROR = N'Lỗi: ' + ERROR_MESSAGE()
		RAISERROR(@ERROR, 16,1)
		ROLLBACK TRAN
		RETURN
	END CATCH

COMMIT TRAN

