--- Dirty Read
--- T1: Đối tác thực hiện thay đổi tên địa chỉ một chi nhánh
--- T2: Khách hàng xem danh sách chi nhánh của một đối tác
----T1
CREATE OR ALTER
PROC USP_D_CHINHANH
@tenmoi nvarchar(100),
@macn varchar(10),
@madt varchar(10)
AS
	BEGIN TRAN
	SET TRAN ISOLATION LEVEL READ COMMITTED
	IF NOT EXISTS ( SELECT *
					FROM CHINHANH_DK CN
					WHERE CN.ID_CHINHANH = @macn)
	BEGIN	
		PRINT N'CHI NHÁNH KHÔNG TỒN TẠI'
		ROLLBACK TRAN
		RETURN 
	END
	IF NOT EXISTS ( SELECT *
					FROM CHINHANH_DK CN 
					WHERE CN.ID_CHINHANH = @macn AND CN.DOITAC=@madt)
	BEGIN	
		PRINT N'KHÔNG CÓ QUYỀN THAO TÁC VÌ CHI NHÁNH NÀY KHÔNG THUỘC VỀ ĐỐI TÁC'
		ROLLBACK TRAN
		RETURN 
	END
	UPDATE CHINHANH_DK
	SET DIACHI = @tenmoi
	WHERE ID_CHINHANH = @macn
	WAITFOR DELAY '00:00:10' 
	IF (SELECT COUNT(*)
		FROM CHINHANH_DK
		WHERE DIACHI = @tenmoi) > 1
	BEGIN
		PRINT N'ĐỊA CHỈ MỚI KHÔNG HỢP LỆ VÌ ĐÃ TỒN TẠI ĐỊA CHỈ NÀY, KHÔNG THỂ CÓ NHIỀU HƠN MỘT CHI NHÁNH CHO MỘT ĐỊA CHỈ'
		ROLLBACK TRAN
		RETURN
	END
	COMMIT TRAN
GO
----T2
CREATE OR ALTER
PROC USP_XEM_CN
@madt varchar(10)
AS
	BEGIN TRAN
	SET TRAN ISOLATION LEVEL READ UNCOMMITTED
	IF NOT EXISTS ( SELECT *
					FROM DOITAC
					WHERE ID_DOITAC = @madt)
	BEGIN 
	PRINT N'KHÔNG TỒN TẠI ĐỐI TÁC NÀY'
	ROLLBACK TRAN
	RETURN
	END
	SELECT TEN_CHINHANH, DIACHI, SDT,TINHTRANG,THOIGIANMO,THOIGIANDONG
	FROM CHINHANH_DK
	WHERE DOITAC = @madt
	COMMIT TRAN
GO