USE QL_DH_GH
GO

--	ADMIN 
EXEC sp_addlogin 'QL_DH_GH_ADMIN', '12345', 'QL_DH_GH';  
GO

EXEC sp_addsrvrolemember 'QL_DH_GH_ADMIN', 'sysadmin';  
GO

-- VODANH
EXEC sp_addlogin 'QL_DH_GH_VODANH', '12345', 'QL_DH_GH';  
GO

CREATE USER VODANH FOR LOGIN QL_DH_GH_VODANH
GO
GRANT EXECUTE ON OBJECT::insert_USER  TO VODANH
GRANT SELECT, INSERT ON dbo.ACCOUNT TO VODANH 
GO

GRANT EXECUTE ON OBJECT::Sp_DangNhap TO VODANH

-- DOITAC
EXEC sp_addlogin 'QL_DH_GH_DOITAC', '12345', 'QL_DH_GH';  
GO

CREATE USER DOITAC FOR LOGIN QL_DH_GH_DOITAC
GO

GRANT SELECT, INSERT, UPDATE ON DOITAC TO DOITAC
GRANT SELECT, INSERT ON HOPDONG TO DOITAC
GRANT SELECT, INSERT ON NHANVIEN_HOPDONG TO DOITAC
GRANT SELECT, INSERT, UPDATE, DELETE ON MONAN TO DOITAC
GRANT SELECT ON DONHANG TO DOITAC
GRANT SELECT ON CT_MONDAT TO DOITAC
GRANT UPDATE ON DONHANG(TINHTRANG) TO DOITAC
GRANT SELECT ON XULI_DONHANG TO DOITAC
GRANT SELECT ON TAIXE(HOTEN,SDT) TO DOITAC
GRANT SELECT, INSERT, UPDATE,DELETE ON CHINHANH_DK TO DOITAC
GRANT SELECT ON KHACHHANG(HOTEN,SDT) TO DOITAC
GO

GRANT EXECUTE ON OBJECT::sp_themCN_DT TO DOITAC
GRANT EXECUTE ON OBJECT:: insert_HOPDONG TO DOITAC
GRANT EXECUTE ON OBJECT::sp_updateMONAN TO DOITAC
GRANT EXECUTE ON OBJECT::insert_DOITAC TO DOITAC
GRANT EXECUTE ON OBJECT::update_DOITAC  TO DOITAC
GRANT EXECUTE ON OBJECT::insert_MONAN TO DOITAC
GRANT EXECUTE ON OBJECT::delete_MONAN TO DOITAC

GO
-- KHACHHANG
EXEC sp_addlogin 'QL_DH_GH_KHACHHANG', '12345', 'QL_DH_GH';  
GO

CREATE USER KHACHHANG FOR LOGIN QL_DH_GH_KHACHHANG
GO

GRANT SELECT, INSERT, UPDATE ON KHACHHANG TO KHACHHANG
GRANT SELECT ON DOITAC(ID_DOITAC,TEN,DIACHI_KD,SL_CHINHANH,LOAI_AMTHUC) TO KHACHHANG
GRANT SELECT ON MONAN TO KHACHHANG
GRANT SELECT, INSERT ON DONHANG TO KHACHHANG
GRANT SELECT, INSERT ON CT_MONDAT TO KHACHHANG
GRANT SELECT ON CHINHANH_DK TO KHACHHANG
GRANT SELECT ON TAIXE(HOTEN,SDT) TO KHACHHANG

GRANT EXECUTE ON OBJECT::sp_KH_MUA TO KHACHHANG
GRANT EXECUTE ON OBJECT::sp_XEMMONAN TO KHACHHANG
GRANT EXECUTE ON OBJECT::sp_KH_XEMDT TO KHACHHANG
GRANT EXECUTE ON OBJECT::insert_KHACHHANG TO KHACHHANG
GRANT EXECUTE ON OBJECT::update_KHACHHANG TO KHACHHANG 

-- TAIXE
EXEC sp_addlogin 'QL_DH_GH_TAIXE', '12345', 'QL_DH_GH';  
GO

CREATE USER TAIXE FOR LOGIN QL_DH_GH_TAIXE
GO
SELECT * FROM KHACHHANG
GRANT SELECT, INSERT ON TAIXE TO TAIXE
GRANT SELECT ON DONHANG TO TAIXE
GRANT SELECT ON CT_MONDAT TO TAIXE
GRANT SELECT ON KHACHHANG(ID_KHACHHANG,HOTEN,SDT_KH) TO TAIXE
GRANT SELECT,UPDATE ON CT_VANCHUYEN TO TAIXE
GRANT UPDATE ON XULI_DONHANG(MATX,NGAYTXNHAN,NGAYKHNHAN) TO TAIXE
GO
GRANT EXECUTE ON OBJECT::show_DONHANG_TAIXE TO TAIXE 
GRANT EXECUTE ON OBJECT::update_TTVC TO TAIXE 
GRANT EXECUTE ON OBJECT::insert_TAIXE TO TAIXE 
GRANT EXECUTE ON OBJECT::update_TAIXE  TO TAIXE 




-- NHANVIEN
EXEC sp_addlogin 'QL_DH_GH_NHANVIEN', '12345', 'QL_DH_GH';  
GO

CREATE USER NHANVIEN FOR LOGIN QL_DH_GH_NHANVIEN
GO

GRANT SELECT, INSERT ON NHANVIEN TO NHANVIEN 
GRANT SELECT ON DOITAC TO NHANVIEN 
GRANT SELECT ON HOPDONG TO NHANVIEN 
GRANT SELECT ON NHANVIEN_HOPDONG TO NHANVIEN
GRANT UPDATE ON HOPDONG(TINHTRANG,NGAYBATDAUDK,NGAYKETTHUCDK) TO NHANVIEN 
GRANT SELECT ON ACCOUNT(MAACC, TENDANGNHAP, MATKHAU) TO NHANVIEN
GRANT UPDATE ON ACCOUNT(MATKHAU) TO NHANVIEN
GRANT SELECT ON NHANVIEN(ID_NHANVIEN) TO NHANVIEN
GRANT SELECT, UPDATE ON NHANVIEN TO NHANVIEN
GO

GRANT EXECUTE ON OBJECT::P_NHANVIENDUYETHOPDONG TO NHANVIEN
GRANT EXECUTE ON OBJECT::P_NV_LOAIBOHOPDONG  TO NHANVIEN
GRANT EXECUTE ON OBJECT::P_NHANVIEN_HOPDONG  TO NHANVIEN
GRANT EXECUTE ON OBJECT::insert_NHANVIEN TO NHANVIEN
GRANT EXECUTE ON OBJECT::update_NHANVIEN  TO NHANVIEN 


-- TẠO ROLE
EXEC SP_ADDROLE 'ROLE_USERS'

-- ADD THÊM USER VÀO ROLE NÀY
EXEC sp_addrolemember 'ROLE_USERS', 'DOITAC'
EXEC sp_addrolemember 'ROLE_USERS', 'KHACHHANG'
EXEC sp_addrolemember 'ROLE_USERS', 'TAIXE'
EXEC sp_addrolemember 'ROLE_USERS', 'NHANVIEN'

-- CẤP QUYỀN CHO ROLE
GRANT SELECT, UPDATE ON ACCOUNT(MATKHAU) TO ROLE_USERS

GRANT SELECT ON CT_MONDAT TO KHACHHANG