USE BANHANG
GO
DROP PROCEDURE dbo.Sp_DangNhap

--VÕ THỊ KIỀU KHANH - 20120305
--NHÂN VIÊN DUYỆT HỢP ĐỒNG 
CREATE OR ALTER
PROCEDURE P_NHANVIENDUYETHOPDONG
				@MaNV VARCHAR(10),
				@MaHD VARCHAR(10),
				@NGAYBATDAU DATE,
				@NGAYKETTHUC DATE
AS
BEGIN TRANSACTION
	--KIỂM TRA XEM CÓ TỒN TẠI NHÂN VIÊN NAY KHÔNG
	BEGIN TRY
	IF NOT EXISTS (SELECT * 
				FROM NHANVIEN NV 
				WHERE ID_NHANVIEN = @MaNV )
	BEGIN
		PRINT @MaNV + N' KHÔNG TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END
	--KIỂM TRA CÓ TỒN TẠI HỢP ĐỒNG NÀY CHƯA
	IF NOT EXISTS (SELECT * 
				FROM HOPDONG HD 
				WHERE ID_HOPDONG = @MAHD )
	BEGIN
		PRINT @MaHD + N' KHÔNG TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END
	--Kiểm tra xem hợp đồng đã được xử lí hay chưa
	--kiểm tra xem hợp đồng đã được xử lí hay chưa
	DECLARE @DADUYET INT
	SET @DADUYET = (SELECT TINHTRANG FROM HOPDONG  WHERE ID_HOPDONG = @MAHD )
	IF (@DADUYET != 0) 
	BEGIN
		PRINT N'Hợp đồng đã được xử lí'
		ROLLBACK TRAN
		RETURN 0
	END

	--set tình trạng duyệt
	SET @DADUYET = 1;
	-- Duyệt hợp đồng
	UPDATE HOPDONG
	SET TINHTRANG = 1, NGAYBATDAUDK = @NGAYBATDAU, NGAYKETTHUCDK = @NGAYKETTHUC
	WHERE HOPDONG.ID_HOPDONG = @MAHD 
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0	
	END CATCH
COMMIT TRANSACTION
RETURN 1
GO

EXEC P_NHANVIENDUYETHOPDONG 'NV0001', 'HD0004','2022-01-01','2022-12-31'

CREATE  OR ALTER PROCEDURE P_NHANVIEN_HOPDONG
				@MaNV VARCHAR(10),
				@MaHD VARCHAR(10),
				@NGAYKIKET DATE
				
AS
BEGIN TRANSACTION
	--KIỂM TRA XEM CÓ TỒN TẠI NHÂN VIÊN NAY KHÔNG
	BEGIN TRY
	IF NOT EXISTS (SELECT * 
				FROM NHANVIEN NV 
				WHERE ID_NHANVIEN = @MaNV )
	BEGIN
		PRINT @MaNV + N' KHÔNG TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END
	--KIỂM TRA CÓ TỒN TẠI HỢP ĐỒNG NÀY CHƯA
	IF NOT EXISTS (SELECT * 
				FROM HOPDONG HD
				WHERE ID_HOPDONG = @MAHD )
	BEGIN
		PRINT @MaHD + N' KHÔNG TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END
	IF EXISTS (SELECT * 
				FROM NHANVIEN_HOPDONG
				WHERE HOPDONG = @MAHD )
	BEGIN
		PRINT @MaHD + N' KHÔNG TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END

	-- Duyệt hợp đồng
	INSERT NHANVIEN_HOPDONG VALUES (@MaHD,@MaNV,@NGAYKIKET)
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0	
	END CATCH
COMMIT TRANSACTION
RETURN 1
GO


EXEC P_NHANVIEN_HOPDONG 'NV0001','HD0003','2022-12-9'

SELECT * FROM HOPDONG

--NHÂN VIÊN LOẠI BỎ HỢP ĐỒNG 
CREATE OR ALTER PROCEDURE P_NV_LOAIBOHOPDONG 
							@MaHD VARCHAR(10),
							@MaNV VARCHAR(10)
AS
BEGIN TRANSACTION
	BEGIN TRY
	IF NOT EXISTS ( SELECT* 
					FROM HOPDONG HD 
					WHERE ID_HOPDONG =@MaHD)
		BEGIN
			PRINT @MaHD + N'KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
	IF (NOT EXISTS (SELECT*
					FROM NHANVIEN
					WHERE ID_NHANVIEN =@MaNV))
		BEGIN
			PRINT @MaNV + N'KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END	
	--kiểm tra xem hợp đồng đã được xử lí hay chưa
	DECLARE @DADUYET INT
	SET @DADUYET = (SELECT TINHTRANG FROM HOPDONG WHERE ID_HOPDONG = @MAHD )
	IF (@DADUYET != 0) 
	BEGIN
		PRINT N'Hợp đồng đã được xử lí'
		ROLLBACK TRAN
		RETURN 0
	END

	--set tình trạng loại bỏ
	SET @DADUYET = 2

	--Không duyệt hợp đồng	
	UPDATE HOPDONG
	SET TINHTRANG = @DADUYET
	WHERE ID_HOPDONG = @MAHD 	
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1
GO


-- GIA HẠN HỢP ĐỒNG

CREATE OR ALTER PROC P_NV_GIAHANHOPDONG
					@MaHD CHAR(10),
					@MaNV CHAR(10), 
					@NGAYKETTHUC DATE
AS
BEGIN TRANSACTION
	BEGIN TRY
	IF NOT EXISTS ( SELECT* 
					FROM HOPDONG HD
					WHERE ID_HOPDONG =@MaHD)
		BEGIN
			PRINT @MaHD + N'KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END
	IF (NOT EXISTS (SELECT*
					FROM NHANVIEN
					WHERE ID_NHANVIEN =@MaNV))
		BEGIN
			PRINT @MaNV + N'KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 0
		END	
	IF NOT EXISTS (SELECT* 
					FROM NHANVIEN NV LEFT JOIN NHANVIEN_HOPDONG NVHD ON NV.ID_NHANVIEN = NVHD.NHANVIEN
					LEFT JOIN HOPDONG HD ON HD.ID_HOPDONG = NVHD.HOPDONG
					WHERE ID_HOPDONG= @MaHD AND ID_NHANVIEN = @MaNV)
		BEGIN 
			PRINT N'NHÂN VIÊN KHÔNG DUYỆT HỢP ĐỒNG NÀY'
			ROLLBACK TRAN 
			RETURN 1
		END
	UPDATE HOPDONG
	SET NGAYKETTHUCDK=@NGAYKETTHUC
	WHERE  ID_HOPDONG= @MaHD
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
COMMIT TRAN
RETURN 1
GO

--------------------------------------------------------------------------------
CREATE OR ALTER PROC sp_themCN_DT @maDT VARCHAR(10),
								  @maCN VARCHAR(10),
								  @tenCN NVARCHAR(100),
								  @diachi NVARCHAR(100),
								  @SDT VARCHAR(10),
								  @TINHTRANG NVARCHAR(50)
								  
AS
BEGIN TRAN
BEGIN TRY
	IF EXISTS(SELECT ID_CHINHANH FROM CHINHANH_DK WHERE ID_CHINHANH= @maCN)
	BEGIN
		PRINT N'Chi nhánh đã tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF EXISTS(SELECT DIACHI FROM CHINHANH_DK WHERE DIACHI = @diachi)
	BEGIN
		PRINT N'Địa chỉ chi nhánh đã tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
		INSERT INTO CHINHANH_DK(ID_CHINHANH,TEN_CHINHANH,DIACHI,SDT,DOITAC,TINHTRANG) VALUES(@maCN,@tenCN,@diachi,@SDT,@maDT,@TINHTRANG)
		
		UPDATE DOITAC 
		SET SL_CHINHANH = SL_CHINHANH +1
		WHERE ID_DOITAC = @madt
		COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Thêm thất bại. Có lỗi trong lúc đăng kí chi nhánh'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1			
GO


--DOITAC CAP NHAT MON AN
CREATE OR ALTER PROC sp_updateMONAN @tenMA VARCHAR(10),
								  	@mta NVARCHAR(100),
									@loai NVARCHAR(50),
									@gia INT
AS
BEGIN TRAN
	IF @tenMA NOT IN (SELECT TENMON FROM MONAN)
	BEGIN
		PRINT N'Món ăn KHÔNG TỒN TẠI'
		ROLLBACK
		RETURN 0
	END
	IF @gia < 0
	BEGIN
		PRINT N'Giá không hợp lệ'
		ROLLBACK TRAN
		RETURN 0
	END
	BEGIN TRY
		UPDATE MONAN
		SET MIEUTAMON = @mta,LOAIMONAN = @loai, GIA = @gia
		WHERE TENMON = @tenMA
		PRINT N'Cập nhật thành công'
		COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Cập nhật thất bại'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1
GO

--KHACH HANG MUA MON AN
CREATE OR ALTER PROC sp_KH_MUA @maMA VARCHAR(10),
							   @sl INT
AS
BEGIN
	IF @maMA NOT IN (SELECT TENMON FROM MONAN)
	BEGIN
		PRINT N'Món ăn KHÔNG TỒN TẠI'
		ROLLBACK TRAN
	END
	IF @sl <= 0
	BEGIN
		PRINT N'Số lượng KHÔNG TỒN TẠI'
		ROLLBACK TRAN
	END
	DECLARE @sl_ton INT = (SELECT SL_TON FROM MONAN WHERE TENMON = @maMA)
	IF @sl_ton < @sl
	BEGIN
		PRINT N'Số lượng hàng còn lại không đủ'
		ROLLBACK TRAN
	END
	BEGIN TRY
		UPDATE MONAN
		SET SL_TON = SL_TON - @sl
		WHERE TENMON = @maMA
		PRINT N'Cập nhật thành công'
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		PRINT N'Cập nhật số lượng tồn thất bại'
		ROLLBACK TRAN
	END CATCH
END
GO

SELECT * FROM MONAN

--KHACH HANG XEM MON AN CUA DOI TAC
CREATE OR ALTER PROC sp_XEMMONAN @madt VARCHAR(10)
AS
BEGIN TRAN
	IF @madt NOT IN (SELECT ID_DOITAC FROM DOITAC)
	BEGIN
		PRINT N'Đối tác KHÔNG TỒN TẠI'
		ROLLBACK TRAN
	END
	BEGIN TRY
		SELECT m.TENMON, m.SL_TON, m.MIEUTAMON, m.LOAIMONAN, m.GIA, c.DIACHI,D.ID_DOITAC
		FROM DOITAC d JOIN CHINHANH_DK c
		ON c.DOITAC = d.ID_DOITAC
		JOIN MONAN m ON m.CHINHANH = c.ID_CHINHANH
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		PRINT N'Xảy ra lỗi khi xem sản phẩm'
		ROLLBACK TRAN
	END CATCH

GO


EXEC sp_XEMMONAN 'DT0001'
--KHACH HANG XEM DANH SACH DOI TAC
CREATE OR ALTER PROC sp_KH_XEMDT
AS
BEGIN TRAN
	BEGIN TRY
		SELECT d.TEN, d.DIACHI_KD, d.SL_CHINHANH,d.LOAI_AMTHUC,s.SDT, D.ID_DOITAC
		FROM DOITAC d JOIN DT_SDT s
		ON d.ID_DOITAC = s.ID_DOITAC
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		PRINT N'Xảy ra lỗi khi xem đối tác'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1
GO


CREATE PROC Sp_DangNhap
	@TENDANGNHAP VARCHAR(50),
	@MATKHAU VARCHAR(50),
	@MAACC VARCHAR(15) OUTPUT,
	@LOAIACC INT OUTPUT
AS
BEGIN
	SET @MAACC = 'NULL'
	IF NOT EXISTS (SELECT MAACC
				FROM ACCOUNT 
				WHERE TENDANGNHAP = @TENDANGNHAP 
				AND MATKHAU = @MATKHAU)
	BEGIN
		PRINT N'Sai tên đăng nhập hoặc mật khẩu'
		RETURN 0
	END
	
	-- lấy mã acc
	SET @MAACC = (SELECT MAACC
				FROM ACCOUNT
				WHERE TENDANGNHAP = @TENDANGNHAP
				AND MATKHAU = @MATKHAU)

	-- lấy loại acc
	SET @LOAIACC = (SELECT LOAIACC
				FROM ACCOUNT
				WHERE TENDANGNHAP = @TENDANGNHAP
				AND MATKHAU = @MATKHAU)

	-- xử lí đăng nhập
	if (@MAACC != 'NULL')
	BEGIN
		PRINT N'Đăng nhập thành công'
		RETURN 1
	END
	ELSE RETURN 0	
END
GO

CREATE OR ALTER PROC insert_USER @id VARCHAR(10),
								 @username NVARCHAR(50),
								 @pwd VARCHAR(50),
								 @loaiTK INT							 
AS
BEGIN TRAN
	IF EXISTS(SELECT  MAACC FROM ACCOUNT WHERE MAACC = @id)
	BEGIN
		PRINT N'Tài khoản đã tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF EXISTS(SELECT TENDANGNHAP FROM ACCOUNT WHERE TENDANGNHAP = @username)
	BEGIN
		PRINT N'Username đã tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	BEGIN TRY
		INSERT INTO ACCOUNT VALUES(@id,@username,@pwd,@loaiTK)
		PRINT N'Thêm thành công'
		COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Có lỗi xảy ra lúc thêm tài khoản. Thêm thất bại.'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1
GO
SELECT * FROM DOITAC

SELECT DH.ID_DONHANG, KH.HOTEN, KH.SDT_KH,DH.NGAYLAP, DH.PHIVANCHUYEN, 
DH.PHUONGTHUCTHANHTOAN, CT.SOLUONG,DH.DIACHIGIAOHANG, DH.PHIVANCHUYEN, DH.TONGTIEN 
FROM DONHANG DH,KHACHHANG KH, CT_MONDAT CT WHERE DH.TRANGTHAIVANCHUYEN LIKE N'Chưa nhận đơn' and DH.KHACHHANG = KH.ID_KHACHHANG and CT.DONHANG = DH.ID_DONHANG
            
			select* from HOPDONG

CREATE OR ALTER PROC insert_HOPDONG @id VARCHAR(10),
									@MST VARCHAR(20),
									@ndd NVARCHAR(50),
									@slcn INT,
									@stk VARCHAR(20),
									@nganhang VARCHAR(50),
									@ngayBD DATE,
									@ngayKT DATE,
									@tinhtrang NVARCHAR(50),
									@doitac VARCHAR(10),
									@thoihanhd INT
AS

BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM DOITAC WHERE ID_DOITAC = @doitac)
	BEGIN
		PRINT N'Đối tác không tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF EXISTS(SELECT * FROM HOPDONG WHERE ID_HOPDONG = @id)
	BEGIN
		PRINT N'ID đã tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END 
	IF @slcn < 1
	BEGIN
		PRINT N'Số lượng chi nhánh không hợp lệ'
		ROLLBACK TRAN
		RETURN 0
	END
	IF @ngayKT < @ngayBD
	BEGIN
		PRINT N'Ngày kết thúc không hợp lệ'
		ROLLBACK TRAN
		RETURN 0
	END
	BEGIN TRY
		INSERT INTO HOPDONG VALUES(@id,@MST,@ndd,@slcn,@stk,@nganhang,@ngayBD,@ngayKT,@tinhtrang,@doitac,@thoihanhd)
		PRINT N'Thêm thành công'
		COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Có lỗi khi thêm hợp đồng. Thêm thất bại'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1
GO


CREATE OR ALTER PROC show_DONHANG_TAIXE @id VARCHAR(10)
AS
BEGIN
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM TAIXE WHERE ID_TAIXE = @id)
	BEGIN
		PRINT N'Tài xế không tồn tại'
		ROLLBACK TRAN
	END 
	DECLARE @kvhd NVARCHAR(50) = (SELECT KHUVUC_HOATDONG FROM TAIXE WHERE ID_TAIXE = @id)
	BEGIN TRY
		SELECT DIACHIGIAOHANG,SDT_NHANHANG,PHIVANCHUYEN,PHUONGTHUCTHANHTOAN,TONGTIEN,CHINHANH,TRANGTHAIVANCHUYEN,ID_DONHANG
		FROM DONHANG
		WHERE CHARINDEX(@kvhd,DIACHIGIAOHANG) > 0 AND TRANGTHAIVANCHUYEN= N'CHỜ NHẬN'
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		PRINT N'Xảy ra lỗi khi hiển thị. Thất bại'
		ROLLBACK TRAN
	END CATCH
END

EXEC show_DONHANG_TAIXE 'TX0004'

CREATE OR ALTER PROC update_TTVC @id_VC VARCHAR(10),
							     @id_DH VARCHAR(10)
AS
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM DONHANG WHERE ID_DONHANG = @id_DH)
	BEGIN
		PRINT N'Đơn hàng không tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF NOT EXISTS(SELECT * FROM CT_VANCHUYEN WHERE ID_VANCHUYEN = @id_VC)
	BEGIN
		PRINT N'ID vận chuyển không tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	BEGIN TRY
		UPDATE DONHANG
		SET TRANGTHAIVANCHUYEN = N'Giao hàng thành công'
		WHERE ID_DONHANG = @id_DH

		UPDATE CT_VANCHUYEN
		SET THOIGIANNHAN = GETDATE()
		WHERE ID_VANCHUYEN = @id_VC
		PRINT N'Cập nhật thành công'
		COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Có lỗi khi cập nhật. Cập nhật thất bại'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1
GO

CREATE OR ALTER PROC insert_CTVC @id_VC VARCHAR(10),
								 @id_DH VARCHAR(10),
								 @id_TX VARCHAR(10)
AS
BEGIN
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM DONHANG WHERE ID_DONHANG = @id_DH)
	BEGIN
		PRINT N'Đơn hàng không tồn tại'
		ROLLBACK TRAN
	END
	IF EXISTS(SELECT * FROM CT_VANCHUYEN WHERE ID_VANCHUYEN = @id_VC)
	BEGIN
		PRINT N'Chi tiết vận chuyển đã tồn tại'
		ROLLBACK TRAN
	END
	IF NOT EXISTS(SELECT * FROM TAIXE WHERE ID_TAIXE = @id_TX)
	BEGIN
		PRINT N'Tài xế không tồn tại'
		ROLLBACK TRAN
	END
	BEGIN TRY
		INSERT INTO CT_VANCHUYEN VALUES(@id_VC,GETDATE(),NULL,@id_DH,@id_TX)
		PRINT N'Thêm thành công'

		UPDATE DONHANG
		SET TRANGTHAIVANCHUYEN = N'Đang giao'
		WHERE ID_DONHANG = @id_DH

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		PRINT N'Có lỗi khi thêm. Thêm thất bại'
		ROLLBACK TRAN
	END CATCH

END

CREATE OR ALTER PROC insert_TAIXE @id_TX VARCHAR(10),
								  @hoten NVARCHAR(50),
								  @cmnd VARCHAR(20),
								  @sdt VARCHAR(10),
								  @dchi NVARCHAR(100),
								  @bsxe VARCHAR(20),
								  @kvhd NVARCHAR(50),
								  @stk VARCHAR(20),
								  @nganhang NVARCHAR(50),
								  @phi MONEY
								 
AS
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM ACCOUNT WHERE MAACC = @id_TX)
	BEGIN
		PRINT N'ID không tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF EXISTS(SELECT * FROM TAIXE WHERE ID_TAIXE = @id_TX)
	BEGIN
		PRINT N'ID đã tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF @phi < 0
	BEGIN
		PRINT N'Phí thuế chân không hợp lệ'
		ROLLBACK TRAN
		RETURN 0
	END
	BEGIN TRY
		INSERT INTO TAIXE VALUES(@id_TX,  @hoten,@cmnd,@sdt,@dchi,@bsxe,@kvhd,@stk,@nganhang,@phi)
		PRINT N'Thêm thành công'
		COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Có lỗi khi thêm tài xế. Thêm thất bại'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1
GO



CREATE OR ALTER PROC update_TAIXE @id_TX VARCHAR(10),
								  @hoten NVARCHAR(50),
								  @cmnd VARCHAR(20),
								  @sdt VARCHAR(10),
								  @dchi NVARCHAR(100),
								  @bsxe VARCHAR(20),
								  @kvhd NVARCHAR(50),
								  @stk VARCHAR(20),
								  @nganhang NVARCHAR(50),
								  @phi MONEY
								 
AS
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM ACCOUNT WHERE MAACC = @id_TX)
	BEGIN
		PRINT N'ID không tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF NOT EXISTS(SELECT * FROM TAIXE WHERE ID_TAIXE = @id_TX)
	BEGIN
		PRINT N'ID Không tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF @phi < 0
	BEGIN
		PRINT N'Phí thuế chân không hợp lệ'
		ROLLBACK TRAN
		RETURN 0
	END
	BEGIN TRY
		UPDATE TAIXE 
		SET ID_TAIXE =@id_TX, HOTEN = @hoten, CMND = @cmnd, SDT = @sdt, DIACHI = @dchi, BIENSOXE = @bsxe, KHUVUC_HOATDONG = @kvhd, SOTAIKHOAN = @stk, NGANHANG = @nganhang, PHITHUECHAN = @phi
		WHERE ID_TAIXE =@id_TX
		COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Có lỗi khi thêm tài xế. Thêm thất bại'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1
GO

CREATE OR ALTER PROC select_DOITAC @id VARCHAR(10)
AS
BEGIN
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM DOITAC WHERE ID_DOITAC = @id)
	BEGIN
		PRINT N'Đối tác không tồn tại'
		ROLLBACK TRAN
	END
	BEGIN TRY
		SELECT * FROM DOITAC WHERE ID_DOITAC = @id
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		PRINT N'Có lỗi đã xảy ra'
		ROLLBACK TRAN
	END CATCH
END
GO

CREATE OR ALTER PROC update_DOITAC @id VARCHAR(10),
								   @ten NVARCHAR(100),
								   @ndd NVARCHAR(50),
								   @tpho NVARCHAR(50),
								   @quan NVARCHAR(50),
								   @sl_don INT,
								   @loaiAT NVARCHAR(50),
								   @dchi NVARCHAR(100)
AS 
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM DOITAC WHERE ID_DOITAC = @id)
	BEGIN
		PRINT N'Đối tác không tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	
	IF @sl_don < 0
	BEGIN
		PRINT N'Số lượng đơn mỗi ngày không hợp lệ'
		ROLLBACK TRAN
		RETURN 0
	END
	BEGIN TRY
		UPDATE DOITAC 
		SET ID_DOITAC =@id, TEN = @ten, NG_DAIDIEN = @ndd, THANHPHO = @tpho, quan = @quan, SL_DONMOINGAY = @sl_don, LOAI_AMTHUC=@loaiAT, DIACHI_KD =@dchi
		WHERE ID_DOITAC =@id
		PRINT N'Thêm thành công'
		COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Có lỗi trong lúc thêm. Thêm thất bại'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1
GO
CREATE OR ALTER PROC insert_DOITAC @id VARCHAR(10),
								   @ten NVARCHAR(100),
								   @ndd NVARCHAR(50),
								   @tpho NVARCHAR(50),
								   @quan NVARCHAR(50),
								   @slcn INT,
								   @sl_don INT,
								   @loaiAT NVARCHAR(50),
								   @dchi NVARCHAR(100)
AS 
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM ACCOUNT WHERE MAACC = @id)
		BEGIN
			PRINT N'ID không tồn tại'
			ROLLBACK TRAN
			RETURN 0
		END
	IF  EXISTS(SELECT * FROM DOITAC WHERE ID_DOITAC = @id)
	BEGIN
		PRINT N'Đối tác tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF @slcn < 1
	BEGIN
		PRINT N'Số lượng chi nhánh không hợp lệ'
		ROLLBACK TRAN
		RETURN 0
	END
	IF @sl_don < 0
	BEGIN
		PRINT N'Số lượng đơn mỗi ngày không hợp lệ'
		ROLLBACK TRAN
		RETURN 0
	END
	BEGIN TRY
		INSERT INTO DOITAC VALUES(@id,@ten,@ndd,@tpho,@quan,@slcn,@sl_don,@loaiAT,@dchi)
		PRINT N'Thêm thành công'
		COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Có lỗi trong lúc thêm. Thêm thất bại'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1
GO
select * from DOITAC
SELECT * from KHACHHANG

CREATE OR ALTER PROC update_KHACHHANG @idkh VARCHAR(10),
								   @ten NVARCHAR(100),
								   @sdt NVARCHAR(50),
								   @diachi NVARCHAR(50)
								   
AS 
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM KHACHHANG WHERE ID_KHACHHANG = @idkh)
	BEGIN
		PRINT N'Đối tác không tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF EXISTS(SELECT * FROM KHACHHANG WHERE SDT_KH = @sdt)
	BEGIN
		PRINT N'SỐ ĐIỆN THOẠI ĐÃ TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END
	
	BEGIN TRY
		UPDATE KHACHHANG 
		SET ID_KHACHHANG =@idkh, HOTEN = @ten, SDT_KH = @sdt, DIACHI = @diachi
		WHERE ID_KHACHHANG =@idkh
		PRINT N'Thêm thành công'
		COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Có lỗi trong lúc thêm. Thêm thất bại'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1
GO

CREATE OR ALTER PROC insert_KHACHHANG @idkh VARCHAR(10),
								   @ten NVARCHAR(100),
								   @sdt NVARCHAR(50),
								   @diachi NVARCHAR(50)
								   
AS 
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM ACCOUNT WHERE MAACC = @idkh)
			BEGIN
				PRINT N'ID không tồn tại'
				ROLLBACK TRAN
				RETURN 0
			END
	IF EXISTS(SELECT * FROM KHACHHANG WHERE ID_KHACHHANG = @idkh)
	BEGIN
		PRINT N'Đối tác tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF EXISTS(SELECT SDT_KH FROM KHACHHANG WHERE SDT_KH = @sdt)
	BEGIN
		PRINT N'SỐ ĐIỆN THOẠI ĐÃ TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END
	
	BEGIN TRY
		INSERT INTO KHACHHANG VALUES (@idkh,@ten,@sdt,@diachi)
		PRINT N'Thêm thành công'
		COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Có lỗi trong lúc thêm. Thêm thất bại'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1
GO

select * from NHANVIEN

CREATE OR ALTER PROC update_NHANVIEN @id VARCHAR(10),
								   @tennv NVARCHAR(100),
								   @email NVARCHAR(50),
								   @ngaysinh  date,
								   @chucvu NVARCHAR(50),
								   @sdt VARCHAR(10),
								   @diachi NVARCHAR(50),
								   @luong MONEY
AS 
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE ID_NHANVIEN = @id)
	BEGIN
		PRINT N'NHÂN VIÊN không tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF EXISTS(SELECT * FROM NHANVIEN WHERE SDT = @sdt)
	BEGIN
		PRINT N'SỐ ĐIỆN THOẠI ĐÃ TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END
	IF EXISTS(SELECT * FROM NHANVIEN WHERE EMAIL= @email)
	BEGIN
		PRINT N'EMAIL ĐÃ TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END

	
	IF @luong < 0
	BEGIN
		PRINT N'Lương không hợp lệ'
		ROLLBACK TRAN
		RETURN 0
	END
	BEGIN TRY
		UPDATE NHANVIEN 
		SET ID_NHANVIEN =@id, TENNHANVIEN = @tennv, EMAIL = @email, NGAYSINH = @ngaysinh, CHUCVU = @chucvu, SDT = @sdt, DIACHI = @diachi, LUONG = @luong
		WHERE ID_NHANVIEN =@id
		PRINT N'cập nhật thành công'
		COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Có lỗi trong lúc thêm. Thêm thất bại'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1
GO

CREATE OR ALTER PROC insert_NHANVIEN @id VARCHAR(10),
								   @tennv NVARCHAR(100),
								   @email NVARCHAR(50),
								   @ngaysinh  DATE,
								   @chucvu NVARCHAR(50),
								   @sdt VARCHAR (15),
								   @diachi NVARCHAR(50),
								   @luong MONEY
AS 
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM ACCOUNT WHERE MAACC = @id)
				BEGIN
					PRINT N'ID không tồn tại'
					ROLLBACK TRAN
					RETURN 0
				END
	IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE ID_NHANVIEN = @id)
	BEGIN
		PRINT N'NHÂN VIÊN không tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF EXISTS(SELECT * FROM NHANVIEN WHERE SDT = @sdt)
	BEGIN
		PRINT N'SỐ ĐIỆN THOẠI ĐÃ TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END
	IF EXISTS(SELECT * FROM NHANVIEN WHERE EMAIL= @email)
	BEGIN
		PRINT N'EMAIL ĐÃ TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	END

	
	BEGIN TRY
		INSERT INTO NHANVIEN VALUES (@id, @tennv,@email,@ngaysinh,@chucvu,@sdt,@diachi, @luong)
		PRINT N'Thêm thành công'
		COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Có lỗi trong lúc thêm. Thêm thất bại'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
RETURN 1
GO

CREATE OR ALTER PROC insert_MONAN @ma VARCHAR(10),
								  @mta NVARCHAR(100),
								  @loai NVARCHAR(50),
								  @gia MONEY,
								  @cn VARCHAR(10),
								  @sl_TON VARCHAR(10)
AS
BEGIN
BEGIN TRAN
	IF EXISTS(SELECT * FROM MONAN WHERE MAMON = @ma)
	BEGIN
		PRINT N'Món ăn đã tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF NOT EXISTS(SELECT * FROM CHINHANH_DK WHERE ID_CHINHANH = @cn)
	BEGIN
		PRINT N'Mã chi nhánh không tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	IF @gia < 0 
	BEGIN
		PRINT N'Giá không hợp lệ'
		ROLLBACK TRAN
		RETURN 0
	END
	IF @sl_TON < 0
	BEGIN
		PRINT N'Số lượng tồn không hợp lệ'
		ROLLBACK TRAN
		RETURN 0
	END
	BEGIN TRY
		INSERT INTO MONAN VALUES(@ma,@mta,@loai,@gia,@cn,@sl_TON)
		PRINT N'Thêm thành công'
		IF @@TRANCOUNT > 0
			COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Thêm thất bại'
		ROLLBACK TRAN
		RETURN 0
	END CATCH

END
CREATE OR ALTER PROC delete_MONAN @ma VARCHAR(10)
AS
BEGIN
BEGIN TRAN
	IF NOT EXISTS(SELECT * FROM MONAN WHERE MAMON = @ma)
	BEGIN
		PRINT N'Món ăn không tồn tại'
		ROLLBACK TRAN
		RETURN 0
	END
	BEGIN TRY
		DELETE FROM MONAN
		WHERE MAMON = @ma
		PRINT N'Xoá thành công'
		IF @@TRANCOUNT > 0
			COMMIT TRAN
		RETURN 1
	END TRY
	BEGIN CATCH
		PRINT N'Xoá thất bại'
		ROLLBACK TRAN
		RETURN 0
	END CATCH
END

