USE QL_DH_GH
GO
--VÕ THỊ KIỀU KHANH-20120305
--ĐỐI TÁC
CREATE OR ALTER  TRIGGER CHECK_DT
ON DOITAC 
INSTEAD OF INSERT, UPDATE 
AS 
BEGIN 
	IF  NOT EXISTS (SELECT * 
					FROM INSERTED I  
					WHERE I.ID_DOITAC IN (SELECT MAACC FROM ACCOUNT))
			BEGIN 
				RAISERROR (N'CHƯA ĐĂNG KÍ TÀI KHOẢN',16,1)
				ROLLBACK TRAN
			END 
	IF EXISTS ( SELECT * 
				FROM INSERTED I 
				WHERE I.ID_DOITAC IS NULL OR I.TEN IS NULL OR I.NG_DAIDIEN IS NULL 
					OR I.DIACHI_KD IS NULL OR I.LOAI_AMTHUC IS NULL
					OR I.LOAI_AMTHUC IS NULL OR I.SL_CHINHANH IS NULL OR I.SL_DONMOINGAY IS NULL
					OR I.THANHPHO IS NULL OR I.QUAN IS NULL)
	BEGIN 
		RAISERROR( N'THÔNG TIN NHẬP KHÔNG HỢP LỆ',16,1)
		ROLLBACK TRAN
	END
	IF EXISTS (SELECT * 
				FROM INSERTED I 
				WHERE I.SL_CHINHANH < 0 OR I.SL_DONMOINGAY <0)
	BEGIN 
		RAISERROR( N'THÔNG TIN NHẬP KHÔNG HỢP LỆ',16,1)
		ROLLBACK TRAN
	END
END

--CHI NHÁNH
CREATE OR ALTER TRIGGER T_CHECK_SL_CHINHANH 
ON DOITAC 
FOR INSERT, UPDATE 
AS
BEGIN 
	IF EXISTS (SELECT* 
				FROM INSERTED I LEFT JOIN HOPDONG HD ON I.ID_DOITAC = HD.DOITAC
				WHERE I.SL_CHINHANH < HD.SL_CHINHANHDK )
	BEGIN 
		RAISERROR (N'SỐ LƯỢNG CHI NHÁNH Ở ĐỐI TÁC NHỎ HƠN SL CHI NHÁNH ĐĂNG KÍ TRONG HỢP ĐỒNG',16,1)
		ROLLBACK TRAN
	END
END
GO 



CREATE OR ALTER TRIGGER T_CHECK_SLCHINHANHDK 
ON HOPDONG
FOR INSERT, UPDATE 
AS
BEGIN
	IF EXISTS (SELECT * 
				FROM INSERTED I LEFT JOIN DOITAC DT ON I.DOITAC = DT.ID_DOITAC
				WHERE I.SL_CHINHANHDK > DT.SL_CHINHANH)
	BEGIN 
		RAISERROR (N'SỐ LƯỢNG CHI NHÁNH Ở ĐỐI TÁC NHỎ HƠN SL CHI NHÁNH ĐĂNG KÍ TRONG HỢP ĐỒNG',16,1)
		ROLLBACK TRAN
	END
END

CREATE OR ALTER TRIGGER CHECK_CNDK 
ON CHINHANH_DK 
FOR INSERT, UPDATE 
AS 
BEGIN 
	IF EXISTS ( SELECT*
				FROM INSERTED I 
				WHERE I.ID_CHINHANH IS NULL OR I.TEN_CHINHANH IS NULL 
				OR I.DIACHI IS NULL OR I.DOITAC IS NULL 
				OR I.SDT IS NULL OR I.THOIGIANDONG IS NULL 
				OR I.THOIGIANMO IS NULL OR I.TINHTRANG IS NULL)
	BEGIN 
		RAISERROR( N'THÔNG TIN NHẬP KHÔNG HỢP LỆ',16,1)
		ROLLBACK TRAN
	END
	IF EXISTS (SELECT * 
				FROM CHINHANH_DK CNDK 
				WHERE CNDK.THOIGIANMO > CNDK.THOIGIANDONG)
	BEGIN 
		RAISERROR(N'THÔNG TIN NHẬP THỜI GIAN MỞ VÀ ĐÓNG KHÔNG HỢP LỆ',16,1)
		ROLLBACK TRAN
	END


	IF EXISTS (SELECT * 
				FROM INSERTED I 
				WHERE I.TINHTRANG NOT LIKE ('BINHTHUONG') AND I.TINHTRANG NOT LIKE( 'TAMNGHI'))
	BEGIN 
		RAISERROR(N'NHẬP TÌNH TRẠNG SAI!!',16,1)
		ROLLBACK TRAN
	END 
END 

SELECT * FROM CHINHANH_DK
--BẢNG HỢP ĐỒNG 

CREATE OR ALTER TRIGGER CHECK_HOPDONG 
ON HOPDONG 
FOR INSERT, UPDATE 
AS
BEGIN
	IF EXISTS (SELECT* 
				FROM INSERTED I 
				WHERE I.DOITAC IS NULL OR I.ID_HOPDONG IS NULL OR I.MST IS NULL
				OR I.NG_DAIDIEN IS NULL OR I.NGANHANG IS NULL OR I.NGAYBATDAUDK IS NULL 
				OR I.NGAYKETTHUCDK IS NULL OR I.SL_CHINHANHDK IS NULL OR I.SO_TAIKHOAN IS NULL
				OR I.TINHTRANG IS NULL)
	BEGIN
		RAISERROR(N'THÔNG TIN NHẬP KHÔNG HỢP LỆ',16,1)
		ROLLBACK TRAN
	END

	IF EXISTS (SELECT* 
				FROM INSERTED I 
				WHERE I.NGAYBATDAUDK > I.NGAYKETTHUCDK )
	BEGIN
		RAISERROR( N'THÔNG TIN NHẬP THỜI GIAN KHÔNG HỢP LỆ',16,1)
		ROLLBACK TRAN
	END

	IF EXISTS (SELECT*
				FROM INSERTED I 
				WHERE I.SL_CHINHANHDK <0 ) 
	BEGIN
		RAISERROR(N'THÔNG TIN SỐ LƯỢNG CHI NHÁNH KHÔNG HỢP LỆ',16,1)
		ROLLBACK TRAN
	END


END 

ALTER TABLE HOPDONG
ADD CONSTRAINT C_MST UNIQUE (MST)
GO

ALTER TABLE HOPDONG 
ADD CONSTRAINT C_TINHTRANG_HD CHECK (TINHTRANG IN (0,1,2))
GO

SELECT* 
FROM HOPDONG

CREATE OR ALTER TRIGGER T_CHECK_NGAY_BAT_DAU 
ON HOPDONG 
FOR INSERT, UPDATE 
AS
BEGIN
IF EXISTS (SELECT* 
			FROM INSERTED I
			WHERE I.NGAYBATDAUDK < (SELECT HD2.NGAYBATDAUDK
									FROM HOPDONG HD2
									WHERE HD2.DOITAC = I.DOITAC))
	BEGIN 
		RAISERROR (N'NGÀY BẮT ĐẦU ĐK SAU PHẢI LỚN HƠN NGÀY ĐĂNG KÍ TRƯỚC ',16,1)
		ROLLBACK TRAN
	END
			
END 

CREATE OR ALTER  TRIGGER CHECK_NHANVIEN
ON NHANVIEN 
FOR UPDATE, INSERT
AS
BEGIN
	IF EXISTS (SELECT* 
				FROM INSERTED I 
				WHERE I.ID_NHANVIEN IS NULL OR I.CHUCVU IS NULL OR I.DIACHI IS NULL OR I.EMAIL IS NULL OR I.LUONG IS NULL 
				OR I.NGAYSINH IS NULL OR I.SDT IS NULL OR I.TENNHANVIEN IS NULL)
	BEGIN
		RAISERROR (N'THÔNG TIN NHẬP KHÔNG HỢP LỆ',16,1)
		ROLLBACK TRAN
	END

	IF EXISTS (SELECT*
				FROM INSERTED I 
				WHERE I.LUONG < 0 )
	BEGIN 
	RAISERROR( N'LƯƠNG KHÔNG HỢP LÊ',16,1)
	ROLLBACK TRAN
	END
END

ALTER TABLE NHANVIEN
ADD CONSTRAINT C_EMAIL_SDT UNIQUE (EMAIL, SDT)
GO


CREATE 
OR ALTER 
TRIGGER CHECK_TAIKHOAN
ON ACCOUNT 
FOR INSERT, UPDATE 
AS 
BEGIN
	IF EXISTS (SELECT*
				FROM INSERTED I 
				WHERE I.LOAIACC IS NULL OR I.LOAIACC IS NULL OR I.MATKHAU IS NULL OR I.MATKHAU IS NULL OR I.TENDANGNHAP IS NULL)
		BEGIN
			RAISERROR( N'THÔNG TIN NHẬP KHÔNG HỢP LỆ',16,1)
			ROLLBACK TRAN
		END
	IF EXISTS (SELECT * 
				FROM INSERTED I 
				WHERE I.LOAIACC != 0 AND I.LOAIACC != 1
				AND I.LOAIACC != 2 AND I.LOAIACC != 3 AND I.LOAIACC != 4)
		BEGIN 
			RAISERROR(N'LOẠI TÀI KHOẢN KHÔNG HỢP LỆ',16,1)
			ROLLBACK TRAN
		END

END
GO

select* from TAIKHOAN

ALTER TABLE TAIKHOAN 
ADD CONSTRAINT C_UNI_K UNIQUE (EMAIL)

ALTER TABLE TAIKHOAN
DROP CONSTRAINT C_UNI_K

ALTER TABLE TAIKHOAN 
ADD CONSTRAINT C_UNI_T UNIQUE (TENTAIKHOAN)


CREATE OR ALTER 
TRIGGER CHECK_CT_VANCHUYEN 
ON CT_VANCHUYEN 
FOR INSERT, UPDATE
AS
BEGIN 
	IF EXISTS (SELECT *
				FROM INSERTED I 
				WHERE I.THOIGIANGIAO > I.THOIGIANNHAN)
	BEGIN
		RAISERROR (N'THỜI GIAN  NHẬP LỖI!!',16,1)
		ROLLBACK TRAN
	END
END

CREATE OR ALTER TRIGGER T_CHECK_THOIGIAN
ON CT_VANCHUYEN 
FOR INSERT, UPDATE 
AS 
BEGIN
	IF EXISTS (SELECT* 
			   FROM CT_VANCHUYEN
			   WHERE THOIGIANGIAO IS NULL )
	BEGIN 
		RAISERROR (N'NGÀY BẮT ĐẦU ĐK SAU PHẢI LỚN HƠN NGÀY ĐĂNG KÍ TRƯỚC ',16,1)
		ROLLBACK TRAN
	END 
END 
-------------------------------------------------------------------------------------------------
--PHẠM MAI THIÊN BẢO- 20120255

-- TRIGGER trên bảng DONHANG
CREATE 
--ALTER
TRIGGER trg_DS
ON DOANHSO
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I WHERE I.DOANHSO IS NULL OR I.NAM IS NULL OR I.THANG IS NULL)
		BEGIN
			PRINT(N'THÔNG TIN NHẬP KHÔNG HỢP LỆ')
			ROLLBACK TRAN
		END
	IF EXISTS (SELECT * FROM INSERTED I WHERE I.DOANHSO < 0)
		BEGIN
			PRINT(N'DOANH SỐ PHẢI LỚN HƠN 0')
			ROLLBACK TRAN
		END
	IF EXISTS(SELECT * FROM INSERTED I WHERE I.THANG NOT BETWEEN 1 AND 12)
	BEGIN
		PRINT N'THÁNG KHÔNG HỢP LỆ'
		ROLLBACK TRAN
	END
END
GO


CREATE
--ALTER
TRIGGER trg_MA
ON MONAN
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I WHERE I.TENMON IS NULL OR I.MIEUTAMON IS NULL OR I.LOAIMONAN IS NULL OR I.GIA IS NULL
				OR SL_TON IS NULL)
		BEGIN
			PRINT(N'THÔNG TIN KHÔNG HỢP LỆ')
			ROLLBACK TRAN
		END
	IF EXISTS (SELECT * FROM INSERTED I WHERE I.GIA < 0)
		BEGIN
			PRINT(N'GIÁ PHẢI LỚN HƠN 0')
			ROLLBACK TRAN
		END
	IF EXISTS(SELECT * FROM MONAN WHERE SL_TON < 0)
	BEGIN
		PRINT N'SỐ LƯỢNG TỒN PHẢI LỚN HƠN 0'
		ROLLBACK TRAN
	END
END
GO


CREATE
--ALTER
proc usp_PHISANPHAM 
	@maDONHang varchar(10), 
	@phISP INt = NULL out
AS
BEGIN
	  (SELECT @phISP = sum(m.GIA*ct.SOLUONG)
			  FROM CT_MONDAT ct, MONAN m
			  WHERE DONHANG = @maDONHang
			  AND m.TENMON = ct.MONAN)
	return @phISP
END
GO

CREATE
--ALTER
TRIGGER trg_DH
ON DONHANG
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I
			   WHERE I.ID_DONHANG IS NULL OR I.NGAYLAP IS NULL OR I.KHACHHANG IS NULL OR I.DIACHIGIAOHANG IS NULL OR I.SDT_NHANHANG IS NULL OR I.PHIVANCHUYEN IS NULL OR I.PHUONGTHUCTHANHTOAN IS NULL OR I.TONGTIEN IS NULL OR I.TRANGTHAIXULY IS NULL OR I.PHANHOI IS NULL)
		BEGIN
			PRINT(N'THÔNG TIN NHẬP KHÔNG HỢP LỆ')
			ROLLBACK TRAN
		END
	IF EXISTS (SELECT * FROM INSERTED I
			   WHERE I.SDT_NHANHANG IN (SELECT d.SDT_NHANHANG
												FROM DONHANG d))
		BEGIN 
			PRINT(N'SỐ ĐIỆN THOẠI KHÁCH HÀNG KHÔNG TỒN TẠI')
			ROLLBACK TRAN
		END
	

	IF EXISTS (SELECT* FROM INSERTED I WHERE I.PHANHOI NOT LIKE 'LIKE' AND I.PHANHOI NOT LIKE 'DISLIKE' AND I.PHANHOI NOT LIKE 'RATING')
		BEGIN
			PRINT(N'PHẢN HỒI SAI CÚ PHÁP ')
			ROLLBACK TRAN
		END
	IF EXISTS (SELECT * FROM INSERTED I WHERE I.TRANGTHAIXULY NOT LIKE'NHANDON' AND I.TRANGTHAIXULY NOT LIKE'CHUANHANDON')
		BEGIN
			PRINT(N'TRẠNG THÁI XỬ LÍ KHÔNG HỢP LỆ ')
			ROLLBACK TRAN
		END
	IF EXISTS (SELECT * FROM INSERTED I WHERE I.TRANGTHAIVANCHUYEN NOT LIKE N'CHỜ NHẬN' AND I.TRANGTHAIVANCHUYEN NOT LIKE N'ĐANG LẤY HÀNG'
				AND I.TRANGTHAIVANCHUYEN NOT LIKE N'ĐANG GIAO' AND I.TRANGTHAIVANCHUYEN NOT LIKE N'GIAO HÀNG THÀNH CÔNG')
		BEGIN
			PRINT(N'TRẠNG THÁI VẬN CHUYỂN KHÔNG HỢP LỆ ')
			ROLLBACK TRAN
		END
END
GO

CREATE
-- ALTER
TRIGGER trg_CT_MONDAT1
ON CT_MONDAT
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS(SELECT * FROM INSERTED I WHERE I.SOLUONG IS NOT NULL OR I.TUYCHON IS NOT NULL)
		BEGIN
			PRINT(N'SỐ LƯỢNG HOẶC TÙY CHỌN SAI CÚ PHÁP')
			ROLLBACK TRAN
		END
	IF EXISTS (SELECT * FROM INSERTED I WHERE I.SOLUONG < 0)
		BEGIN
			PRINT(N'SỐ LƯỢNG PHẢI LỚN HƠN 0')
			ROLLBACK TRAN
		END
END

GO

CREATE
--ALTER
TRIGGER trg_KHACHHANG
ON KHACHHANG
INSTEAD OF INSERT, UPDATE
AS
BEGIN
	IF  NOT EXISTS (SELECT * 
					FROM INSERTED I  
					WHERE I.ID_KHACHHANG IN (SELECT MAACC  FROM ACCOUNT))
			BEGIN 
				RAISERROR (N'CHƯA ĐĂNG KÍ TÀI KHOẢN',16,1)
				ROLLBACK TRAN
			END 
	IF EXISTS (SELECT * FROM INSERTED I WHERE I.HOTEN IS NULL OR I.DIACHI IS NULL OR I.SDT_KH IS NULL)
		BEGIN
			PRINT(N'LỖI NHẬP LIỆU')
			ROLLBACK TRAN
		END
	IF EXISTS (SELECT * FROM INSERTED I WHERE I.SDT_KH  IN (SELECT SDT_KH FROM KHACHHANG))
		BEGIN
			PRINT(N'SỐ ĐIỆN THOẠI TỒN TẠI')
			ROLLBACK TRAN
		END
END

GO
CREATE
-- ALTER
TRIGGER trg_TAIXE
ON TAIXE
INSTEAD OF INSERT, UPDATE
AS
BEGIN
	IF  NOT EXISTS (SELECT * 
					FROM INSERTED I  
					WHERE I.ID_TAIXE IN (SELECT MAACC  FROM ACCOUNT))
			BEGIN 
				RAISERROR (N'CHƯA ĐĂNG KÍ TÀI KHOẢN',16,1)
				ROLLBACK TRAN
			END 
	IF EXISTS (SELECT * FROM INSERTED I WHERE I.BIENSOXE IS NULL OR I.CMND IS NULL OR I.DIACHI IS NULL OR I.HOTEN IS NULL OR I.KHUVUC_HOATDONG IS NULL OR I.NGANHANG IS NULL OR I.PHITHUECHAN IS NULL OR I.SDT IS NULL)
		BEGIN
			PRINT(N'THÔNG TIN NHẬP VÀO KHÔNG ĐƯỢC MANG GIÁ TRỊ NULL')
			ROLLBACK TRAN
		END
	IF EXISTS (SELECT * FROM INSERTED I WHERE I.CMND IN (SELECT CMND FROM TAIXE) 
										OR I.BIENSOXE IN(SELECT BIENSOXE FROM TAIXE) 
										OR I.SDT IN (SELECT SDT FROM TAIXE))
		BEGIN
			PRINT(N'CMND, BIỂN SỐ XE HOẶC SỐ DIỆN THOẠI ĐÃ CÓ ')
			ROLLBACK TRAN
		END
	IF EXISTS (SELECT* FROM INSERTED I WHERE I.PHITHUECHAN<0)
		BEGIN
			PRINT(N'PHÍ THUẾ CHÂN PHẢI LỚN HƠN 0')
			ROLLBACK TRAN
		END
END

